//============================= data for LIst Order table =============================

export const ordersData = [
  {
    id: "#CM9801",
    user: "Natali Craig",
    project: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "In Progress",
    profilePic: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: "#CM9802",
    user: "Kate Morrison",
    project: "CRM Admin pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "Complete",
    profilePic: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: "#CM9803",
    user: "Drew Cano",
    project: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "Pending",
    profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: "#CM9804",
    user: "Orlando Diggs",
    project: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "Approved",
    profilePic: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: "#CM9805",
    user: "Andi Lane",
    project: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "Rejected",
    profilePic: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: "#CM9806",
    user: "Carmen Jones",
    project: "E-commerce Site",
    address: "Pinecrest St. Los Angeles",
    date: "Just now",
    status: "In Progress",
    profilePic: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: "#CM9807",
    user: "Lee Roy",
    project: "Mobile App UI",
    address: "5th Avenue New York",
    date: "3 minutes ago",
    status: "Complete",
    profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: "#CM9808",
    user: "Zara Lunde",
    project: "Blog Website",
    address: "King St. Miami",
    date: "30 minutes ago",
    status: "Pending",
    profilePic: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: "#CM9809",
    user: "Jayden Flores",
    project: "Corporate Website",
    address: "Maple Drive Houston",
    date: "2 hours ago",
    status: "Approved",
    profilePic: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: "#CM9810",
    user: "Eliza Clark",
    project: "Dashboard Design",
    address: "Silverton Blvd Denver",
    date: "1 day ago",
    status: "Rejected",
    profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: "#CM9811",
    user: "Bryan Holmes",
    project: "Landing Page",
    address: "Emerald Bay Portland",
    date: "Feb 1, 2023",
    status: "In Progress",
    profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: "#CM9812",
    user: "Melinda Lee",
    project: "E-commerce Site",
    address: "Cedar Ridge Austin",
    date: "Jan 28, 2023",
    status: "Complete",
    profilePic: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: "#CM9813",
    user: "James Miller",
    project: "Mobile App UI",
    address: "Lakeview Rd Chicago",
    date: "1 hour ago",
    status: "Pending",
    profilePic: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: "#CM9814",
    user: "Sandra Bell",
    project: "Corporate Website",
    address: "Grand St. Seattle",
    date: "3 hours ago",
    status: "Approved",
    profilePic: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: "#CM9815",
    user: "Fredric Hunt",
    project: "Blog Website",
    address: "Mountain Rd Las Vegas",
    date: "1 day ago",
    status: "Rejected",
    profilePic: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: "#CM9816",
    user: "Gina Edwards",
    project: "Admin Dashboard",
    address: "Birchwood Drive Dallas",
    date: "2 days ago",
    status: "In Progress",
    profilePic: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: "#CM9817",
    user: "Oliver Scott",
    project: "Client Project",
    address: "Sunset Blvd Chicago",
    date: "Yesterday",
    status: "Complete",
    profilePic: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: "#CM9818",
    user: "Laura Clark",
    project: "App Landing Page",
    address: "Shady Ln San Diego",
    date: "2 minutes ago",
    status: "Pending",
    profilePic: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: "#CM9819",
    user: "Oscar Green",
    project: "CRM Admin pages",
    address: "Riverside Ave Sacramento",
    date: "4 hours ago",
    status: "Approved",
    profilePic: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: "#CM9820",
    user: "Monica Lopez",
    project: "Dashboard Design",
    address: "Park Ave New York",
    date: "Yesterday",
    status: "Rejected",
    profilePic: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: "#CM9821",
    user: "Victor Chen",
    project: "E-commerce Site",
    address: "Vista Del Mar Los Angeles",
    date: "2 hours ago",
    status: "In Progress",
    profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: "#CM9822",
    user: "Zoe Price",
    project: "Landing Page",
    address: "Oakwood Road San Francisco",
    date: "3 days ago",
    status: "Complete",
    profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: "#CM9823",
    user: "Ethan Morris",
    project: "Corporate Website",
    address: "Fifth Ave Chicago",
    date: "Jan 10, 2023",
    status: "Pending",
    profilePic: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: "#CM9824",
    user: "Ava Sullivan",
    project: "Client Project",
    address: "Broadway St. Boston",
    date: "2 days ago",
    status: "Approved",
    profilePic: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: "#CM9825",
    user: "Liam Harris",
    project: "Blog Website",
    address: "Pleasant Hill Miami",
    date: "3 hours ago",
    status: "Rejected",
    profilePic: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: "#CM9826",
    user: "Lily Walker",
    project: "Mobile App UI",
    address: "Eagle Way Dallas",
    date: "Just now",
    status: "In Progress",
    profilePic: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: "#CM9827",
    user: "Eli Brown",
    project: "Admin Dashboard",
    address: "Clearwater Blvd Los Angeles",
    date: "1 day ago",
    status: "Complete",
    profilePic: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: "#CM9828",
    user: "Daniel Taylor",
    project: "Landing Page",
    address: "Riverwood Road Portland",
    date: "2 hours ago",
    status: "Pending",
    profilePic: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: "#CM9829",
    user: "Isabella Carter",
    project: "CRM Admin pages",
    address: "Pine Bluff St New York",
    date: "A minute ago",
    status: "Approved",
    profilePic: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: "#CM9830",
    user: "George Foster",
    project: "E-commerce Site",
    address: "Avenue St. Sacramento",
    date: "4 hours ago",
    status: "Rejected",
    profilePic: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: "#CM9831",
    user: "Charlotte Shaw",
    project: "App Landing Page",
    address: "Tanglewood Rd Austin",
    date: "Yesterday",
    status: "In Progress",
    profilePic: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: "#CM9832",
    user: "Amelia Ward",
    project: "Client Project",
    address: "Apple St Miami",
    date: "1 hour ago",
    status: "Complete",
    profilePic: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: "#CM9833",
    user: "Samuel Diaz",
    project: "Mobile App UI",
    address: "Oak St. Houston",
    date: "2 days ago",
    status: "Pending",
    profilePic: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: "#CM9834",
    user: "Benjamin Lee",
    project: "Corporate Website",
    address: "Elm St. New York",
    date: "3 hours ago",
    status: "Approved",
    profilePic: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: "#CM9835",
    user: "Ella Adams",
    project: "Blog Website",
    address: "Mariner St Los Angeles",
    date: "2 minutes ago",
    status: "Rejected",
    profilePic: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: "#CM9836",
    user: "Mason Jones",
    project: "Admin Dashboard",
    address: "Skyline Blvd San Francisco",
    date: "2 hours ago",
    status: "In Progress",
    profilePic: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: "#CM9837",
    user: "Emily Hall",
    project: "Landing Page",
    address: "Valley Rd Chicago",
    date: "3 hours ago",
    status: "Complete",
    profilePic: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: "#CM9838",
    user: "Lucas Wright",
    project: "CRM Admin pages",
    address: "Spring St. Miami",
    date: "4 hours ago",
    status: "Pending",
    profilePic: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: "#CM9839",
    user: "Harper King",
    project: "E-commerce Site",
    address: "Willow Rd Los Angeles",
    date: "1 day ago",
    status: "Approved",
    profilePic: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: "#CM9840",
    user: "Joshua Scott",
    project: "Mobile App UI",
    address: "Pine Ave San Francisco",
    date: "Yesterday",
    status: "Rejected",
    profilePic: "https://randomuser.me/api/portraits/women/21.jpg",
  },
];
